apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minipaas.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "minipaas.selectorLabels" . | nindent 4 }}
    app: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}