apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minipaas.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Les URLs de connexion sont CONSTRUITES ici, à partir des identifiants
  # (values.secrets.yaml) et des noms de Service (fixes, comme à l'étape 2).
  DATABASE_URL: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"
  REDIS_ADDR: "redis:6379"
  RABBITMQ_URL: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.rabbitmq.password }}@rabbitmq:5672/"