apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minipaas.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.api.port | quote }}
  RABBITMQ_QUEUE: {{ .Values.api.queueName | quote }}
