apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minipaas.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "minipaas.selectorLabels" . | nindent 4 }}
    app: redis
  ports:
    - port: 6379
      targetPort: 6379